-- ═══════════════════════════════════════════════════════════════════════════
-- alge · 100 seed conversations
--
-- Purpose: an empty globe asks a visitor to be the first person to speak, which
-- almost nobody does. These 100 questions give the space something to be, so a
-- real user arrives with something to answer instead of a blank sphere.
--
-- HONESTY: every row is authored by '.bro' — the house account. None of them
-- impersonate a person. Nothing here pretends to be user-generated.
--
-- Arrangement: 6 categories balanced (18/18/18/16/15/15), interleaved so no
-- cluster lights up alone, placed across 42 real cities weighted toward the
-- IIT Mandi beachhead, and back-dated across ~34 days so the space reads as
-- having a history rather than a single dump.
--
-- Reversible — remove every seeded row with:
--     DELETE FROM questions WHERE name = '.bro';
-- (replies to them cascade only if you drop those first — see the note below)
-- ═══════════════════════════════════════════════════════════════════════════

INSERT INTO questions (name, body, category, lat, lon, created_at) VALUES
  ('.bro', 'If AI can already do the work I''m training for, what am I actually training for?', 'ai & future', 31.78, 77.59, now() - interval '48960 minutes'),
  ('.bro', 'What''s the real reason most campus startups die after demo day?', 'build & startup', 31.14, 76.34, now() - interval '48507 minutes'),
  ('.bro', 'What''s the one question you never got to ask your teacher?', 'study & gyaan', -34.52, 18.47, now() - interval '48055 minutes'),
  ('.bro', 'What conversation are you postponing?', 'life', 23.05, 88.73, now() - interval '47602 minutes'),
  ('.bro', 'Who here is building something and needs hands?', 'meet people', 25.1, 54.68, now() - interval '47150 minutes'),
  ('.bro', 'What''s the best question anyone has ever asked you?', 'random', 31.46, 77.49, now() - interval '46697 minutes'),
  ('.bro', 'What''s the last thing a machine will learn to do?', 'ai & future', 52.09, -0.28, now() - interval '46244 minutes'),
  ('.bro', 'How do you find a co-founder before everyone scatters?', 'build & startup', -6.74, 106.57, now() - interval '45792 minutes'),
  ('.bro', 'Why does school teach what to learn but never how to learn?', 'study & gyaan', 13.28, 80.84, now() - interval '45339 minutes'),
  ('.bro', 'Who did you never thank properly?', 'life', -1.06, 36.27, now() - interval '44887 minutes'),
  ('.bro', 'Who''s solving the same problem as you without knowing it?', 'meet people', 31.23, 77.24, now() - interval '44434 minutes'),
  ('.bro', 'What would you do with one free year and nobody judging?', 'random', 41.28, -73.82, now() - interval '43981 minutes'),
  ('.bro', 'Which job that everyone calls safe will disappear first?', 'ai & future', 31.8, 34.26, now() - interval '43529 minutes'),
  ('.bro', 'What did you build that nobody wanted — and when did you know?', 'build & startup', 17.25, 79.07, now() - interval '43076 minutes'),
  ('.bro', 'Which subject did you memorise perfectly and never understand?', 'study & gyaan', -23.05, -46.97, now() - interval '42624 minutes'),
  ('.bro', 'What are we all pretending is fine when it isn''t?', 'life', 31.19, 76.9, now() - interval '42171 minutes'),
  ('.bro', 'Which quiet person in your class should everyone actually talk to?', 'meet people', 38.15, -121.96, now() - interval '41718 minutes'),
  ('.bro', 'Which rule exists for no reason anymore?', 'random', -34.57, -58.98, now() - interval '40655 minutes'),
  ('.bro', 'Is it dishonest to use AI for work you put your own name on?', 'ai & future', 18.09, 74.28, now() - interval '40202 minutes'),
  ('.bro', 'Is it braver to start, or to stop?', 'build & startup', 7.12, 3.36, now() - interval '39750 minutes'),
  ('.bro', 'What would you remove from the syllabus tomorrow?', 'study & gyaan', 31.33, 76.6, now() - interval '39297 minutes'),
  ('.bro', 'What will you regret not doing this year?', 'life', 52.59, 14.0, now() - interval '38844 minutes'),
  ('.bro', 'Who do you know that thinks completely unlike you?', 'meet people', 52.58, 20.52, now() - interval '38392 minutes'),
  ('.bro', 'What''s your most unpopular opinion, said plainly?', 'random', 22.43, 72.69, now() - interval '37939 minutes'),
  ('.bro', 'What did we lose when we stopped struggling to find an answer?', 'ai & future', 38.08, 127.29, now() - interval '37487 minutes'),
  ('.bro', 'What''s a business hiding in plain sight in your city?', 'build & startup', 31.61, 76.41, now() - interval '37034 minutes'),
  ('.bro', 'What''s worth learning that has no exam attached to it?', 'study & gyaan', 35.41, 140.23, now() - interval '36581 minutes'),
  ('.bro', 'What does almost everyone misunderstand about you?', 'life', 41.57, 28.76, now() - interval '36129 minutes'),
  ('.bro', 'Who did you meet once and never follow up with?', 'meet people', 26.35, 75.57, now() - interval '35676 minutes'),
  ('.bro', 'What''s the weirdest thing that taught you the most?', 'random', 52.63, 5.44, now() - interval '35224 minutes'),
  ('.bro', 'Will our kids think it was strange that we typed?', 'ai & future', 28.78, 76.63, now() - interval '34771 minutes'),
  ('.bro', 'When is dropping out actually rational, and when is it a story you tell yourself?', 'build & startup', 0.84, 104.13, now() - interval '34318 minutes'),
  ('.bro', 'Which book changed how you think, not just what you know?', 'study & gyaan', 47.97, 8.66, now() - interval '33866 minutes'),
  ('.bro', 'Which fear did you quietly outgrow without noticing?', 'life', 25.79, 91.25, now() - interval '33413 minutes'),
  ('.bro', 'Which senior should every junior meet before they leave?', 'meet people', 19.36, -98.53, now() - interval '32350 minutes'),
  ('.bro', 'What tiny thing about right now will you miss the most?', 'random', 19.53, 72.49, now() - interval '31897 minutes'),
  ('.bro', 'Who decides what an AI is allowed to refuse to say?', 'ai & future', -34.47, 151.19, now() - interval '31444 minutes'),
  ('.bro', 'How much money do you really need before you can start? Honestly.', 'build & startup', -36.42, 175.18, now() - interval '30992 minutes'),
  ('.bro', 'What did the toppers understand that the rest of us didn''t?', 'study & gyaan', 9.9, 75.67, now() - interval '30539 minutes'),
  ('.bro', 'What''s the kindest thing a stranger ever did for you?', 'life', 58.95, 18.53, now() - interval '30087 minutes'),
  ('.bro', 'Who wants to co-work on Sundays?', 'meet people', 13.56, 77.51, now() - interval '29634 minutes'),
  ('.bro', 'What would you put in a time capsule to be opened in 2050?', 'random', 43.16, -79.72, now() - interval '29181 minutes'),
  ('.bro', 'What should a 17-year-old start learning today that AI won''t touch in ten years?', 'ai & future', 31.92, 77.57, now() - interval '28729 minutes'),
  ('.bro', 'What''s the smallest thing you could ship this week?', 'build & startup', 31.03, 76.26, now() - interval '28276 minutes'),
  ('.bro', 'Is a degree an education, or a receipt?', 'study & gyaan', -34.49, 18.6, now() - interval '27824 minutes'),
  ('.bro', 'What would you tell yourself five years ago, in one sentence?', 'life', 23.12, 88.61, now() - interval '27371 minutes'),
  ('.bro', 'Who would you want in the room when you make a hard decision?', 'meet people', 24.97, 54.72, now() - interval '26918 minutes'),
  ('.bro', 'Which everyday object deserves far more credit than it gets?', 'random', 31.58, 77.55, now() - interval '26466 minutes'),
  ('.bro', 'If AI writes the code, who actually understands the system?', 'ai & future', 52.04, -0.41, now() - interval '26013 minutes'),
  ('.bro', 'Who did you stop building with, and was it the right call?', 'build & startup', -6.79, 106.7, now() - interval '25561 minutes'),
  ('.bro', 'What''s the best thing you ever learned outside a classroom?', 'study & gyaan', 13.4, 80.78, now() - interval '24497 minutes'),
  ('.bro', 'When did you last change your mind about something big?', 'life', -1.19, 36.23, now() - interval '24044 minutes'),
  ('.bro', 'Which mentor changed your direction with a single sentence?', 'meet people', 31.3, 77.36, now() - interval '23592 minutes'),
  ('.bro', 'What''s a question you''re a little scared to know the answer to?', 'random', 41.31, -73.96, now() - interval '23139 minutes'),
  ('.bro', 'What''s the most overhyped AI promise of this year?', 'ai & future', 31.69, 34.34, now() - interval '22687 minutes'),
  ('.bro', 'What does a first paying customer actually feel like?', 'build & startup', 17.39, 79.09, now() - interval '22234 minutes'),
  ('.bro', 'Which teacher changed your life and never found out?', 'study & gyaan', -23.14, -47.07, now() - interval '21781 minutes'),
  ('.bro', 'What do you do when nobody is watching that you''re proud of?', 'life', 31.18, 77.04, now() - interval '21329 minutes'),
  ('.bro', 'Who is looking for the exact skill you already have?', 'meet people', 38.24, -122.05, now() - interval '20876 minutes'),
  ('.bro', 'What did you believe strongly at 15 that''s completely gone now?', 'random', -34.7, -58.97, now() - interval '20424 minutes'),
  ('.bro', 'Does using AI to think make you a worse thinker, or just a faster one?', 'ai & future', 18.19, 74.36, now() - interval '19971 minutes'),
  ('.bro', 'Which piece of famous founder advice is just survivorship bias?', 'build & startup', 7.1, 3.23, now() - interval '19518 minutes'),
  ('.bro', 'How do you keep studying something you''re bad at without quitting?', 'study & gyaan', 31.25, 76.71, now() - interval '19066 minutes'),
  ('.bro', 'Which friendship ended without a fight, and why?', 'life', 52.72, 13.97, now() - interval '18613 minutes'),
  ('.bro', 'Who in your city is worth a coffee and never gets asked?', 'meet people', 52.46, 20.46, now() - interval '18161 minutes'),
  ('.bro', 'What''s genuinely overrated that everyone seems to love?', 'random', 22.47, 72.82, now() - interval '17708 minutes'),
  ('.bro', 'What happens to entry-level work when nobody needs juniors anymore?', 'ai & future', 38.14, 127.17, now() - interval '17255 minutes'),
  ('.bro', 'Would you rather own 5% of something big or 100% of something small?', 'build & startup', 31.49, 76.47, now() - interval '16192 minutes'),
  ('.bro', 'What''s a concept you only understood years after the exam?', 'study & gyaan', 35.54, 140.27, now() - interval '15739 minutes'),
  ('.bro', 'What''s the hardest thing you''ve had to forgive?', 'life', 41.51, 28.64, now() - interval '15287 minutes'),
  ('.bro', 'Whose work do you admire from a distance and have never told them?', 'meet people', 26.32, 75.7, now() - interval '14834 minutes'),
  ('.bro', 'If you had to teach one thing for an hour, what would it be?', 'random', 52.75, 5.37, now() - interval '14381 minutes'),
  ('.bro', 'Which human skill is quietly becoming more valuable, not less?', 'ai & future', 28.65, 76.61, now() - interval '13929 minutes'),
  ('.bro', 'What''s the most useful thing you learned from a failure nobody saw?', 'build & startup', 0.92, 104.24, now() - interval '13476 minutes'),
  ('.bro', 'Should we be taught how to be wrong properly?', 'study & gyaan', 47.98, 8.52, now() - interval '13024 minutes'),
  ('.bro', 'What are you doing only because it''s expected of you?', 'life', 25.69, 91.35, now() - interval '12571 minutes'),
  ('.bro', 'Who taught you something important without meaning to?', 'meet people', 19.5, -98.53, now() - interval '12118 minutes'),
  ('.bro', 'What''s the strangest advice you were given that actually worked?', 'random', 19.43, 72.4, now() - interval '11666 minutes'),
  ('.bro', 'Would you tell someone their therapist was an AI?', 'ai & future', -34.46, 151.33, now() - interval '11213 minutes'),
  ('.bro', 'How do you put a price on something you made yourself?', 'build & startup', -36.34, 175.07, now() - interval '10761 minutes'),
  ('.bro', 'What''s the most useless thing you were ever graded on?', 'study & gyaan', 9.76, 75.69, now() - interval '10308 minutes'),
  ('.bro', 'What makes a day feel like it counted?', 'life', 59.06, 18.61, now() - interval '9855 minutes'),
  ('.bro', 'Who are you avoiding that you should probably call?', 'meet people', 13.53, 77.37, now() - interval '9403 minutes'),
  ('.bro', 'What would you ask a version of yourself from 2040?', 'random', 43.09, -79.6, now() - interval '8339 minutes'),
  ('.bro', 'Name a problem AI made worse while claiming to solve it.', 'ai & future', 32.04, 77.53, now() - interval '7887 minutes'),
  ('.bro', 'What do investors say they want, versus what they actually fund?', 'build & startup', 30.9, 76.2, now() - interval '7434 minutes'),
  ('.bro', 'If you could re-attend one lecture of your life, which one?', 'study & gyaan', -34.43, 18.73, now() - interval '6981 minutes'),
  ('.bro', 'What''s a small habit that quietly changed your life?', 'life', 23.16, 88.48, now() - interval '6529 minutes'),
  ('.bro', 'Which two people you know should meet each other?', 'meet people', 24.85, 54.78, now() - interval '6076 minutes'),
  ('.bro', 'What''s something true you have never said out loud?', 'random', 31.71, 77.59, now() - interval '5624 minutes'),
  ('.bro', 'Is learn to code still honest advice to give a teenager?', 'ai & future', 51.96, -0.52, now() - interval '5171 minutes'),
  ('.bro', 'Is a co-founder a partner, or a hedge against loneliness?', 'build & startup', -6.81, 106.83, now() - interval '4718 minutes'),
  ('.bro', 'How do you know when you actually understand something?', 'study & gyaan', 13.51, 80.69, now() - interval '4266 minutes'),
  ('.bro', 'Who would you call at 3am — and do they know that?', 'life', -1.32, 36.22, now() - interval '3813 minutes'),
  ('.bro', 'What is the one thing you''d want an AI never to be allowed to do?', 'ai & future', 31.4, 77.45, now() - interval '3361 minutes'),
  ('.bro', 'What would you build if it could never make money?', 'build & startup', 41.3, -74.09, now() - interval '2908 minutes'),
  ('.bro', 'What''s a skill everyone assumes you have and nobody ever teaches?', 'study & gyaan', 31.6, 34.44, now() - interval '2455 minutes'),
  ('.bro', 'If intelligence gets cheap, what gets expensive?', 'ai & future', 17.52, 79.07, now() - interval '2003 minutes'),
  ('.bro', 'What is genuinely stopping you from starting today?', 'build & startup', -23.25, -47.15, now() - interval '1550 minutes'),
  ('.bro', 'Which obvious idea took you the longest to accept?', 'study & gyaan', 31.21, 77.17, now() - interval '1098 minutes');
